spring.application.name=Rating

server.port=8086

# DB connection (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.oytjwiibyvglfdrbiovn
spring.datasource.password=postgres@123

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT for Supabase / PgBouncer
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.data-source-properties.prepareThreshold=0